//
// Created by anton on 26/03/2024.
//

#ifndef INC_3_CREAROBJASOCIACION_VETERINARIO_H
#define INC_3_CREAROBJASOCIACION_VETERINARIO_H


class Veterinario {

};


#endif //INC_3_CREAROBJASOCIACION_VETERINARIO_H
